version: "3.8"

services:
  app:
    build: .
    container_name: fathers-day-app
    restart: unless-stopped
    expose:
      - 80
    networks:
      - web

  nginx:
    image: nginx:alpine
    container_name: fathers-day-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.reverseproxy.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - app
    networks:
      - web

  certbot:
    image: certbot/certbot
    container_name: fathers-day-certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: /bin/sh -c
    # The command below is for initial certificate request. For renewal, use `certbot renew`.
    command: >
      "trap exit TERM; while :; do certbot certonly --webroot --webroot-path=/var/www/certbot
      --email your-email@example.com --agree-tos --no-eff-email
      -d faustoday.duckdns.org; sleep 12h & wait $${!}; done"
    networks:
      - web

networks:
  web:
    driver: bridge
